### ISSUE TITLE
Problem Provisioning in Azure

### ISSUE THREAD

**Issue by kenlangdon** [chef-cft/national-parks-demo#25]
When performing a `terraform apply` in the National Parks Demo `...terraform/azure` directory.  The following error occurs:

```Error: Error applying plan:

4 error(s) occurred:

* azurerm_virtual_machine.permanent-peer: error executing "/tmp/terraform_1759793539.sh": Process exited with status 1
* azurerm_virtual_machine.mongodb: error executing "/tmp/terraform_1114131904.sh": Process exited with status 1
* azurerm_virtual_machine.haproxy: error executing "/tmp/terraform_1395668471.sh": Process exited with status 1
* azurerm_virtual_machine.app: error executing "/tmp/terraform_1564002431.sh": Process exited with status 1```

Logging into each machine and manually executing the appropriate scripts allowed us to repair and complete the provisioning but this is not ideal.

**Comment by ChefRycar** [comment]
I'm not sure if this is the same issue, but I think I ran into something similar in one of my runs, and the issue turned out to be a special character in my azureuser password that was doing funky things to the string interpolation. Worked for me when I changed it to only use alphanumeric characters.

**Comment by kenlangdon** [comment]
Thanks for that suggestion as it was spot on.  Changing the password to use only alphanumeric characters fixed it.  I believe an update to the azure tfvars.example is in order.

**Comment by ChefRycar** [comment]
Fair 'nuff. We should probably remove the example password entirely so folks aren't tempted to use it and create their own. I'll create a new issue to track that -- should be an easy enough fix.

**Comment by ChefRycar** [comment]
Opened [this issue](https://github.com/chef-cft/national-parks-demo/issues/33) to track updating the tfvars password example, and referenced this issue. Closin' it out!

**Comment by kenlangdon** [comment]
Excellent!  Thanks Nick!
