### ISSUE TITLE
if us-west-2d is selected terraform fails 

### ISSUE THREAD

**Issue by ericcalabretta** [chef-cft/national-parks-demo#30]
I'm sure we've all seen this, normally a destroy/apply loop will pick a different AZ and get you past this error. 

It is very annoying and we should refactor at some point to remove this issue. Putting this out here so we remember, and folks don't think it's an issue unique to them.

```* aws_instance.permanent_peer: 1 error(s) occurred:

* aws_instance.permanent_peer: Error launching source instance: Unsupported: Your requested instance type (m4.xlarge) is not supported in your requested Availability Zone (us-west-2d). Please retry your request by not specifying an Availability Zone or choosing us-west-2c, us-west-2a, us-west-2b.
```

**Comment by jmery** [comment]
@ericcalabretta Put in a PR to update the default instance type in `variables.tf` from `m4.xlarge` to m5.xlarge`.  Until that is merged, you can override the default instance type in your `tfvars` file.
