### ISSUE TITLE
Update tfvars.example files with explanatory comments

### ISSUE THREAD

**Issue by ChefRycar** [chef-cft/national-parks-demo#42]
While our documentation instructs folks to create a `terraform.tfvars` file from the examples provided in each folder's `tfvars.example`, it's not immediately obvious what some of the variables are used for without parsing the README for details. 

To make things less opaque, suggest updating the example files with comments briefly describing what each variable or group of variables is used for.

**Comment by scottpgallagher** [comment]
Created a PR for this.
