### ISSUE TITLE
SUDO timeout hit in azure terraform apply

### ISSUE THREAD

**Issue by ChefRycar** [chef-cft/national-parks-demo#54]
It looks like the `terraform/azure` config will sometimes take long enough in the initial yum update that its sudo session times out, and it continually prompts for the sudo password, halting the deploy.

I'm not sure yet if it's just a matter of updating an image somewhere, but at the very least as a workaround I found this seemed to work: 

In `terraform/azure/main.tf`, reaplace all instances of:

`"sudo groupadd hab",`

with:

`"echo ${var.azure_image_password} | sudo -S groupadd hab"`

I'll see if I can't poke around later in the week and see about getting an official fix in place. Might be worth managing sudoers directly -- will report back.

**Comment by ericcalabretta** [comment]
fixed via https://github.com/chef-cft/national-parks-demo/pull/69
